<a href="https://colab.research.google.com/github/B-Lina/ProgramacionII-UNAHUR/blob/main/Practica_3_Arreglos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ![alt text](https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Python-logo-notext.svg/50px-Python-logo-notext.svg.png) **Práctica 3: Arreglos uni y multidimensionales** ![alt text](https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Python-logo-notext.svg/50px-Python-logo-notext.svg.png)

En este trabajo práctico, vamos a trabajar con arreglos uni y multidimensionales en Python. Recuerden crear una copia de este archivo en su ***Google Drive*** para tener permisos de edición.



### Martin: **martin.pustilnik@unahur.edu.ar** ###

### **Ejercicio 1**

Escribir un programa que le pida al usuario que ingrese 10 números  enteros (primero uno, luego otro, y así hasta que el usuario ingrese 10 numeros). Al final, el programa debe imprimir los números que fueron ingresados en orden inverso, la suma total de los valores y el promedio.

In [1]:
import numpy as np

suma = 0
promedio = 1
arreglo = np.zeros(10,int)
for i in range(10):
    numero = int(input(f"Ingrese el numero en la posicion {i+1}" ))
    arreglo[i] = numero
    print(arreglo[i])
    suma = arreglo[i]+suma
    
print(suma)
promedio = suma /10
print(promedio)

for i in reversed(range(10)):
    print(arreglo[i])

20
30
40
50
60
70
80
90
10
11
461
46.1
11
10
90
80
70
60
50
40
30
20


### **Ejercicio 1b**

Escribir un progrma que imprima un subarreglo sin la primera ni la ultima posicion.

Se recomienda usar el operador ":"   arreglo[desde:hasta:paso]

Por ejemplo si arr2 = arr[0:len(arr)], arr2 copia todo el arreglo arr.

In [14]:
import numpy as np

arreglo = [1,5,6,4,5,7]
arreglo_nuevo = arreglo[1:5:1]
print(arreglo_nuevo)

[5, 6, 4, 5]


In [1]:
import numpy as np

vector = np.zeros((3),int)

vector[0] = int(input("ingrese un numero"))
vector[1] = int(input("ingrese un numero"))
vector[2] = int(input("ingrese un numero"))

for indice in range(len(vector)):
  vector[indice] = int(input("ingrese un numero"))
  print(indice, vector[indice])

for indice in range(len(vector)):
  vector[indice] = indice*indice
  print(indice, vector[indice])

for indice in reversed(range(len(vector))):
  print(indice, vector[indice])

0 8
1 9
2 10
0 0
1 1
2 4
2 4
1 1
0 0


### **Ejercicio 2**

Escribir una función que recibe un arreglo de enteros por parámetro y lo retorna con el contenido desplazado una posición hacia la derecha: el primero pasa a ser el segundo, el segundo pasa a ser el tercero y así sucesivamente. El último pasa a ser el primero.

Luego, escribir un programa que cargue un arreglo con valores ingresados por el usuario y llame a la función con ese arreglo. Mostrar el contenido del arreglo por pantalla, antes y después de la función.

Por ejemplo:

Arreglo original = [2, 4, 1, 5, 7, 9]

Arreglo desplazado = [9, 2, 4, 1, 5, 7]

In [ ]:
#                   0  1  2  3  4  5  de 0 a len(arreglo)-1
import numpy as np
arreglo = np.array([2, 4, 1, 5, 7, 9])
arreglo2 = np.array([3, 2, 4])

def desplazar(arr:np.array):
    aux = arr[len(arr)-1]
    print(aux)
    print("-------------------")
    for i in reversed (range(len(arr))):
        arr[i]=arr[i-1]
        print(arr[i])
        
    arr[0]=aux
    print("-------------------")
    print(arr[0])
desplazar(arreglo)
print(arreglo)

9
-------------------
7
5
1
4
2
7
-------------------
9
[9 2 4 1 5 7]


### **Ejercicio 3**

Desarrollar una función que inserte un elemento en un arreglo de enteros dada la posición de inserción. Al insertar un elemento en una posición, se produce un desplazamiento a la derecha, si el arreglo estaba lleno, el último elemento se pierde.

Por ejemplo:

Si insertamos el elemento 5 en la posicion 3 del arreglo:

Arreglo antes de insertar = [2, 4, 1, 7, 6, 2]

Arreglo despues de insertar = [2, 4, 1, ***5***, 7, 6]

In [10]:
import numpy as np

#               0  1  2  3  4  5
arr = np.array([2, 4, 1, 7, 6, 0])
"""
def insertarArr(arr:np.array,numero:int,posicion:int):
    aux = 0
    for i in range (len(arr)):
        if arr[i] == arr[posicion]:
            arr[i] = arr[numero]
        
    for i in range (len(arr)):
        print(arr[i])
"""
def insertarArr(arr: np.array, numero: int, posicion: int):
    # Desplazar a la derecha desde el final hasta la posición
    #print(len(arr)-1)
    #print(" ------")
    for i in range(len(arr) - 1, posicion, -1):
        #print(arr[i])
        arr[i] = arr[i - 1]
        #print(arr[i])
        #print(" nnn-----")
    # Insertar el nuevo número
    arr[posicion] = numero
    # Imprimir el arreglo
    for i in range(len(arr)):
        print(arr[i])

insertarArr(arr,5,3)
print(arr)

2
4
1
5
7
6
[2 4 1 5 7 6]


### **Ejercicio 3 bis**  Escribir una funcion que reciba dos arreglos y devuelva otro como resultado de la suma elemento a elemento de los arreglos recibidos como parametro

Si

a = [1,2,3]
b = [4,3,4]

entonces tenemos que devolver

[5,5,7]

In [19]:
import numpy as np

v10 = np.array([2, 4, 1, 7, 6, 2])
v20 = np.array([5, 6, 7, 8, 9, 5])

def sumarArreglos (arr1:np.array,arr2:np.array):
    arrSuma = np.zeros(len(arr1)-1,int)
    for i in range (len(arr1)-1):
        arrSuma[i] = arr1[i] + arr2[i]
        print(arrSuma[i])
    return arrSuma

sumarArreglos(v10,v20)

    

7
10
8
15
15


array([ 7, 10,  8, 15, 15])

### **Ejercicio 4**

Escribir una función que elimine el elemento que ocupa una determinada posición de un arreglo de enteros.  Al eliminar se debe mantener la continuidad, es decir, los elementos a la derecha del eliminado, deben desplazarse a la izquierda un lugar.

Por ejemplo:

Si eliminamos el elemento de la posicion 2 del arreglo:

Arreglo antes de eliminar = [4, 3, **5**, 8, 6, 7]

Arreglo despues de eliminar = [4, 3, 8, 6, 7, 0]

In [34]:
arreglo = np.array([4, 3, 5, 8, 6, 7])

def eliminarElemento(arr:np.array,posicion:int):
    for i in range (posicion,len(arr)-1):
        arr[i] = arr[i+1]
        print(arr[i])
    arreglo[-1] = 0


eliminarElemento(arreglo,4)
print(arreglo)

7
[4 3 5 8 7 0]


### **Ejercicio 5**

Escribir una función que elimine todas las apariciones de un determinado elemento de un arreglo de enteros.

In [2]:
arreglo = [1,2,3,2,4,5,6,2,7,8,9,2]

def eliminarRepetido(arr:np.array,numero:int):
    numeroRepeticiones = 0
    for i in range (len(arr)-1):
        if arr[i] == numero:
            numeroRepeticiones =+ i
            arr[i] = arr[i+1]
            print(numeroRepeticiones)

eliminarRepetido(arreglo,2)
print(arreglo)

1
3
7
[1, 3, 3, 4, 4, 5, 6, 7, 7, 8, 9, 2]


### **Ejercicio 6**

Escribir un programa que crea y cargar dos matrices de tamaño 3x3, las suma y muestra el resultado.

In [59]:
import numpy as np

matriz1 = np.random.randint(0,10,(3,3))
matriz2 = np.random.randint(0,10,(3,3))

sumaArreglos = np.zeros((3,3),int)
for i in range (len(matriz1)):
    for j in range (len(matriz1[0])):
        sumaArreglos[i][j]= matriz1[i][j] + matriz2[i][j]

print("Matriz 1:")
print(matriz1)
print("Matriz 2:")
print(matriz2)
print("Suma de matrices:")
print(sumaArreglos)

Matriz 1:
[[6 8 1]
 [9 7 8]
 [2 6 2]]
Matriz 2:
[[0 3 9]
 [7 1 3]
 [8 5 1]]
Suma de matrices:
[[ 6 11 10]
 [16  8 11]
 [10 11  3]]


### **Ejercicio 7**

Escribir una función que recibe una matriz y la rellena de la siguiente forma:

En la posición M[ n , m ]

debe contener n + m.


In [15]:
mat1 = np.array([[0,10,20],[1,1,1],[2,2,2],[2,2,2]])
matrizPosiciones = np.zeros((4,3),int)

for i in range(len(mat1)):
    for j in range (len(mat1[0])):
        matrizPosiciones[i][j] =i+j

print(mat1)

print(matrizPosiciones)

[[ 0 10 20]
 [ 1  1  1]
 [ 2  2  2]
 [ 2  2  2]]
[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]]


### **Ejercicio 8**

Desarrollar una función que recibe una matriz cuadrada de números reales (N x N) por parámetro y calcula la suma de los elementos que están por encima de la diagonal principal (excluyendo la diagonal).

En el ejemplo de la imagen, la función deberia retornar: *b + c + f*

![texto alternativo](https://economipedia.com/wp-content/uploads/Captura-de-Pantalla-2019-07-29-a-les-13.18.05-1.png)

In [ ]:
#Muestra la suma de los numeros fuera de la diagonal
mat1 = np.array([[0,10,20],[1,1,1],[2,2,2]])
sumaDiagonal = 0
for i in range (len(mat1)):
    for j in range (len(mat1[0])):
        if i!=j:
            sumaDiagonal += mat1[i][j] 
print(sumaDiagonal)


#Muestra la suma de los numeros sobre la diagonal
mat1 = np.array([[0,10,20],[1,1,1],[2,2,2]])
suma = 0
for i in range(len(mat1)):
    for j in range(len(mat1[0])):
        if j > i:
            suma += mat1[i][j]

print(suma)

36
31


### **Ejercicio 9**

Escribir una función que retorna *True* si una matriz cuadrada de enteros es matriz diagonal y *False* en caso contrario.

Una matriz diagonal es una matriz que tiene ceros en todos sus elementos, menos en la diagonal principal.

In [35]:
matrizCuadrada = np.array([[1,0,0],[0,1,0],[0,0,1]])
matrizCuadrada2 = np.array([[1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,1]])

"""
[[1 0 0]
 [0 1 0]
 [0 0 1]]

"""

def esDiagonal(matriz):
    for i in range(len(matriz)):
        for j in range(len(matriz[0])):
            if i != j and matriz[i][j] != 0:
                return False
    return True

print(matrizCuadrada)
print(esDiagonal(matrizCuadrada))

print(matrizCuadrada2)
print(esDiagonal(matrizCuadrada2))

[[1 0 0]
 [0 1 0]
 [0 0 1]]
True
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
True


### **Ejercicio 10**

Escribir una función que retorna *True* si una matriz cuadrada de enteros es simétrica y *False* en caso contrario.

Una matriz simétrica es como la de la imagen (no importan los elementos de la diagonal principal):

![texto alternativo](https://economipedia.com/wp-content/uploads/Captura-de-Pantalla-2019-09-23-a-les-15.58.25.png)

In [ ]:
mat1 = np.array([[1,0,0],[1,1,1],[2,2,2]])
mat2 = np.array([['d','s','e'],['s','d','a'],['e','a','d']])

# [0,1] = [1,0], [0,2] = [2,0], [1,2] = [2,1]
def matrizSimetrica(matriz:np.array) -> np.array:
    for i in range (len(matriz)):
        for j in range (len(matriz[0])):
            if matriz[i][j] != matriz[j][i]:
                return False
        return True
    

matrizSimetrica(mat2)


False

### **Comentario**

En los ejercicios que usan cadenas de caracteres, pueden usar el tipo *str*, salvo que necesiten modificar elementos de la cadena luego de crearla, en ese caso, tienen que usar arreglos de caracteres.

### **Ejercicio 11**

Escribir 3 procedimientos que reciben una cadena de caracteres y..:
- Imprima los dos primeros caracteres.
- Imprima los tres últimos caracteres.
- Imprima la cadena cada dos caracteres. Por ej.: 'recta' debería imprimir 'rca'

In [77]:
nombres = "Carolina"

def primerosCaracteres(cadena:str)->str:
    return cadena[:2]

def ultimosCaracteres(cadena:str)->str:
    return cadena[-3:]

def dosCaracteres(cadena:str) -> str:
    return cadena[::2]

In [78]:
primerosCaracteres(nombres)
ultimosCaracteres(nombres)
dosCaracteres(nombres)

'Crln'

### **Ejercicio 12**

Escribir una función que recibe una cadena de caracteres y un caracter y retorna una nueva cadena que tiene el caracter entre cada letra de la cadena de entrada.

Por ej si la cadena es: ' separar ' y el caracter es: ' x ', debería retornar ' sxexpxaxrxaxr '

In [4]:
def intercalar_caracter(cadena: str, caracter: str) -> str:
    nueva_cadena = ""
    for letra in cadena:
        nueva_cadena += letra + caracter
    return nueva_cadena

# Ejemplo de uso:
print(intercalar_caracter("separar", "x"))  # Imprime 'sxexpxaxrxaxr'

sxexpxaxrxaxrx


### **Ejercicio 13**

Escribir una función que recibe un arreglo variables de tipo "Tiempo" (TDA del ejercicio 4 del TP de TDA) y retorna un nuevo arreglo solo con los tiempos que son mayores a una hora (1:00:00).

Escribir un programa para probar a la función.

Nota: Van a tener que copiar el TDA "Tiempo" en el bloque de código de abajo y para que un *print* de un vector de variables de tipo "Tiempo" funcione, tienen que programar la operacion "\_\_repr__()" en el TDA "Tiempo".

In [ ]:
def validarTipo(variable,nombre,tipo, condicion=True):
    if isinstance(variable,tipo) and condicion:
        return variable
    else:
        raise Exception ("La variable" + nombre + "deber ser de tipo "+str(tipo))
    
class Tiempo:
    def __init__(self,horas:int,minutos:int,segundos:int):
        self._horas = horas 
        self._minutos = validarTipo(minutos,"minutos",int,0 <= minutos <=59)
        self._segundos = validarTipo(segundos,"segundos",int,0 <= segundos <= 59)
    
    def segundos(self):
        return self._segundos
    def minutos(self):
        return self._minutos
    def horas(self):
        return self._horas
    
    def __repr__(self) -> str:
        return f"{self._horas:02d}:{self._minutos:02d}:{self._segundos:02d}"
    
    def tiempoaSegundos(self):
        return self._horas * 3600 + self._minutos * 60 + self._segundos
    
def tiemposMayoresaUnaHora(fechas) -> list:
    fechasHoras = []
    for tiempo in fechas:
        if tiempo.tiempoaSegundos() > 3600:
            fechasHoras.append(tiempo)
    return fechasHoras

In [30]:

mi_tiempo = Tiempo(1,00,00)

print(mi_tiempo.tiempoaSegundos())  # Imprime 9015

fechasComprobacion = np.array([
    Tiempo(0, 59, 59),
    Tiempo(1, 0, 1),
    Tiempo(2, 10, 0),
    Tiempo(0, 30, 0)
], dtype=object)

print(tiemposMayoresaUnaHora(fechasComprobacion))

3600
[01:00:01, 02:10:00]


### **Ejercicio 14**

Una de las aplicaciones de matrices en programación es la representación y procesamiento de imágenes. Vamos a ver algunas cosas que se pueden hacer. Para esto primero tenemos que cargarnos una imagen en el colab y generar una matriz a partir de ella.

- Descarguen el archivo "felix.csv" del siguiente link:
https://drive.google.com/file/d/1B18uu-11gnEtdlL3rTA2nolZKKWShxRY/view?usp=sharing
- Suban el archivo "felix.csv" al "colab" para poder cargarlo con el programa de Python de abajo (haciendo click en el icono de la carpeta ![texto alternativo](https://i.ibb.co/jzqwMsc/carpeta.png), de arriba a la izquierda y luego en "Subir")
- Completen el programa, procesando a la imagen guardada en la matriz "felix" para obtener las imágenes de la siguiente figura (La "A" es la imagen original), pueden hacer funciones que generen cada transformación en la imagen:

![texto alternativo](https://i.ibb.co/BcW3mwF/felix-results.png)

In [5]:
import numpy as np
import matplotlib.pyplot as plt
import copy as cp

###Lectura del archivo en la matriz#####
felix = np.genfromtxt('felix.csv', delimiter=',')
########################################

######Para mostrar matriz como imagen###########
plt.imshow(felix)
plt.show()
########################################

print(felix[0:4,0:4])

FileNotFoundError: felix.csv not found.